apiVersion: apps/v1
kind: Deployment
metadata:
  name: refuel
  labels:
    app: refuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refuel
  template:
    metadata:
      labels:
        app: refuel
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: Refuel
          image: username/Refuel:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/refuels'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/refuels'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5